title: Using of IAM User from External IP address
id: b3877a46-b2ff-4766-b36e-5ed311058cdd
status: test
description: Detects the using of IAM user from outside AWS range
author: asafaprozper
date: 2022/11/01
tags:
    - attack.initial_access
    - attack.t1078.001
logsource:
    product: aws
    service: cloudtrail
detection:
    selection_source:
        userIdentity.type: IAMUser
    filter:
        sourceIPAddress:
            - '*.amazonaws.com'
            - 'AWS Internal'
    condition: selection_source and not filter
falsepositives:
    - Sometimes DevOps using a strong IAM user (such as, "jenkins" or "teamcity") from their personal workstation for troubleshooting
    - Detecting access from other AWS accounts, to avoid that you will need to add all AWS IP address ranges to exclude
level: high